/**
 *
 * Triangular, pentagonal, and hexagonal
 *
 * Problem 45
 *
 * Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
 * 
 * Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
 * Pentagonal 	  	Pn=n(3n-1)/2 	  	1, 5, 12, 22, 35, ...
 * Hexagonal 	  	Hn=n(2n-1) 	  	1, 6, 15, 28, 45, ...
 *
 * It can be verified that T(285) = P(165) = H(143) = 40755.
 *
 * Find the next triangle number that is also pentagonal and hexagonal.
 *
 */

/*
for (var t = 286; t < 100000; t++) {
    var tri = t * (t + 1) / 2;
    for (var p = 165; p < 100000; p++) {
        var pen = p * (3 * p - 1 ) / 2;
        if (pen == tri) {
            for (var h = 286; h < 100000; h++) {
                var hex = h * ( 2 * h - 1);
                if (tri == hex) {
                    console.log(tri);
                }
            }
        }
    }
}
*/


function T(n) {
    return n * (n + 1) / 2;
}

function P(n) {
    return n * (3 * n - 1) / 2;
}

function H(n) {
    return n * (2 * n - 1);
}

var answer = 0;
var storage = [];
for (var n = 165; n < 100000; n++) {
    var tmp = [P(n)];
    if (n > 285) {
        tmp.push(T(n));
        tmp.push(H(n));
    }
    
    for (var i = 0; i < tmp.length; i++) {
        if (storage[tmp[i]] == undefined) {
            storage[tmp[i]] = 0;
        }
        
        storage[tmp[i]]++;
        
        if (storage[tmp[i]] == 3) {
            answer = tmp[i];
            break;
        }
    }
    
    if (answer > 0) {
        break;
    }
}


console.log(answer);